spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://deepvalley-mysql.ch6g0iw4mna8.ap-northeast-2.rds.amazonaws.com:3306/mydb
    username: myroot
    password: mypassword
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          useUnicode: true
          characterEncoding: utf8mb4

logging:
  file:
    name: ./app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"