spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/local
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: jjhhyb.deepvalley.dialect.CustomH2Dialect
    hibernate:
      ddl-auto: create