spring:
  application:
    name: deepvalley
  profiles:
    active: dev,secrets
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        jdbc: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace

oauth:
  kakao:
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

management:
  endpoints:
    web:
      exposure:
        include: "*"